[tool.poetry]
name = "agents-playground"
version = "0.1.0"
description = ""
authors = ["Samuel Holloway <sholloway@gmail.com>"]

[tool.poetry.scripts]
agents = "agents_playground.main:main"

[tool.poetry.dependencies]
python = "^3.9"
dearpygui = "^1.1"

[tool.poetry.dev-dependencies]
mypy = "^0.910"
pudb = "^2021.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
