[tool.poetry]
name = "agents-playground"
version = "0.1.0"
description = "A prototyping environment."
authors = ["Samuel Holloway <sholloway@gmail.com>"]

[tool.poetry.scripts]
agents = "agents_playground.main:main"

[tool.poetry.dependencies]
python = "^3.10"
dearpygui = "^1.7.2"
tomli = "^2.0.1"
psutil = "^5.9.2"

[tool.poetry.dev-dependencies]
mypy = "^0.942"
pudb = "^2022.1.1"
py-spy = "^0.3.11"
pytest = "7.1.1"
pytest-mock = "^3.7.0"
ptpython = "^3.0.20"
bpython = "^0.22.1"
pytest-cov = "^3.0.0"
pdoc = "^11.0.0"
matplotlib = "^3.5.1"
line-profiler = "^3.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = [
  "tests"
]
console_output_style = "count"