[tool.poetry]
name = "agents-playground"
version = "0.1.0"
description = "A prototyping environment."
authors = ["Samuel Holloway <sholloway@gmail.com>"]

[tool.poetry.scripts]
agents = "agents_playground.main:main"

[tool.poetry.dependencies]
python = "^3.9"
dearpygui = "^1.1.1"

[tool.poetry.dev-dependencies]
mypy = "^0.910"
pudb = "^2021.2.2"
py-spy = "^0.3.11"
pytest = "^6.2.5"
pytest-mock = "^3.6.1"
ptpython = "^3.0.20"
bpython = "^0.22.1"
pytest-cov = "^3.0.0"
pdoc3 = "^0.10.0"
matplotlib = "^3.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = [
  "tests"
]
console_output_style = "count"