[simulation.ui]
title = 'Our Town'
description = 'A simulation of a small town.'
instructions = 'Click the start button to begin the simulation.'

[scene]
cell_size = [20, 20]
height = 5000

# Define the factory
[[scene.entities.factories]]
id = 1
title = "The Factory"
location = [12, 1] 
width = 40          
height = 5
color=[0, 0, 0]
fill=[221, 160, 221]
renderer='ot_building_renderer'
update_method='ot_update_building'

# Define the schools
[scene.entities]
schools = [
  { id = 1, title = "Elementry School",   location = [12, 7], width = 8, height = 3, color=[0, 0, 0], fill=[0, 249, 153], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 2, title = "Middle School",      location = [21, 7], width = 8, height = 3, color=[0, 0, 0], fill=[0, 249, 153], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 3, title = "High School",        location = [30, 7], width = 8, height = 3, color=[0, 0, 0], fill=[0, 249, 153], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 4, title = "Community College",  location = [39, 7], width = 8, height = 3, color=[0, 0, 0], fill=[0, 250, 120], renderer='ot_building_renderer', update_method='ot_update_building'},
  { id = 5, title = "University",         location = [48, 7], width = 8, height = 3, color=[0, 0, 0], fill=[0, 250, 120], renderer='ot_building_renderer', update_method='ot_update_building' }  
]

churches = [
  { id = 1, title = "Temple",           location = [12, 15], width = 3, height = 3, color=[0, 0, 0], fill=[229, 229, 249], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 2, title = "Mosque",           location = [18, 15], width = 4, height = 3, color=[0, 0, 0], fill=[229, 229, 249], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 3, title = "Presbyterian",     location = [24, 15], width = 8, height = 3, color=[0, 0, 0], fill=[229, 229, 249], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 4, title = "Catholic Church",  location = [34, 15], width = 8, height = 3, color=[0, 0, 0], fill=[229, 229, 249], renderer='ot_building_renderer', update_method='ot_update_building' }
]

main_street_businesses = [
  { id = 1, title = "Murv's\nDiner",          location = [12, 23], width = 3, height = 3, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 2, title = "Fancy Pants\nResturant", location = [16, 23], width = 6, height = 3, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 3, title = "Coffee\nBar",            location = [23, 23], width = 3, height = 2, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 4, title = "Bar",                    location = [27, 23], width = 3, height = 3, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 5, title = "Bowling Ally",           location = [31, 23], width = 10, height = 3, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
  
  
  { id = 6, title = "Roller Rink",        location = [12, 32], width = 10, height = 3, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 7, title = "Comic\nShop",        location = [23, 32], width = 3, height = 3, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 8, title = "Spices",             location = [27, 32], width = 2, height = 3, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 9, title = "Pawn\nShop",         location = [30, 32], width = 3, height = 3, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 10, title = "Discount\nRack",    location = [34, 32], width = 3, height = 3, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 11, title = "Barbershop",        location = [38, 32], width = 4, height = 3, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 12, title = "Salon",             location = [43, 32], width = 3, height = 3, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 13, title = "Fortune\nTeller",   location = [47, 32], width = 3, height = 3, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
]

parks = [
  { id = 1, title = "Peaceful Park",      location = [12, 36], width = 26, height = 4, color=[100, 230, 100], fill=[100, 230, 100], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 2, title = "Last Stop Cemetery", location = [39, 39], width = 13, height = 6, color=[100, 230, 100], fill=[100, 230, 100], renderer='ot_building_renderer', update_method='ot_update_building' },
]

gov_buildings = [
  { id = 1, title = "City Hall",location = [240, 860], width = 80, height = 80, color=[60, 230, 100], fill=[216, 112, 214], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 2, title = "Court",    location = [340, 860], width = 60, height = 80, color=[100, 230, 100], fill=[216, 112, 214], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 3, title = "Jail",     location = [420, 880], width = 120, height = 60, color=[100, 230, 100], fill=[216, 112, 214], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 4, title = "Prison",   location = [560, 860], width = 200, height = 80, color=[100, 230, 100], fill=[216, 112, 214], renderer='ot_building_renderer', update_method='ot_update_building' },
]

big_box_stores = [
  { id = 1, title = "Mega-mart", description="Grocery/Home Supply Store", location = [240, 960], width = 600, height = 100, color=[100, 230, 100], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' }
] 

# Residential Area: Single Family Homes, Apartment Buildings
apartment_buildings = [
  { id = 1, title = "Tower 1", location = [240, 1080], width = 185, height = 60, color=[100, 230, 100], fill=[63, 104, 224], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 2, title = "Tower 2", location = [445, 1080], width = 185, height = 60, color=[100, 230, 100], fill=[63, 104, 224], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 3, title = "Tower 3", location = [650, 1080], width = 185, height = 60, color=[100, 230, 100], fill=[63, 104, 224], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 4, title = "Tower 4", location = [855, 1080], width = 185, height = 60, color=[100, 230, 100], fill=[63, 104, 224], renderer='ot_building_renderer', update_method='ot_update_building' }
]

# Roads...
# The roads need to support graph traversal. 
# Options
# 1. Use a line segment path. Don't worry about having the roads curve. 
#    I don't think it's worth the hassel of fooling around with curve libraries for the simulation.
# 
# 2. The current implementation of a line path doesn't account for branching paths.
#    Probably need a higher level abstraction that groups multiple paths.
#    For example "graph" which is a connection of points and edges. That can then be 
#    Rendered and traversed. Try to see if this can be implented as a single entity
#    to avoid having to create additional TOML parsing scene builders. 

# streets are long and just define their start and end points since they're all linear.
# They are rendered as disconneted line segments that can have text associated with them.
# A street is 2 cells wide.
# An interstate is 4 cells wide. The traffic is in lanes.
# The end points are the center line.
streets = [
  { id = 1, label='Interstate',       start = [5, 0], end = [5, 100], lanes=4, color=[211, 211, 211], renderer='ot_interstate_renderer', update_method='ot_update_interstate'},
  { id = 2, label='Factory Drive',    start = [7, 3], end = [12, 3],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  
  { id = 3, label='Education Lane',   start = [7, 13],  end = [51, 13],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  { id = 4, label='Elementry Street', start = [14, 10], end = [14, 12],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  { id = 5, label='Middle Street',    start = [23, 10], end = [23, 12],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  { id = 6, label='HS Street',        start = [32, 10], end = [32, 12],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  { id = 7, label='CC. Street',       start = [41, 10], end = [41, 12],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  { id = 8, label='U Street',         start = [50, 10], end = [50, 12],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  
  { id = 9, label='Religion Row', start = [7, 21],  end = [52, 21],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  { id = 10, label='T Street',    start = [13, 18], end = [13, 20],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  { id = 11, label='M Street',    start = [20, 18], end = [20, 20],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  { id = 12, label='P Street',    start = [30, 18], end = [30, 20],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  { id = 13, label='P Street',    start = [39, 18], end = [39, 20],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  
  { id = 14, label='Main Street', start = [7, 29],  end = [52, 29],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  { id = 15, label='Diner',       start = [13, 26], end = [13, 28],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  { id = 16, label='Resturant',   start = [18, 26], end = [18, 28],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  { id = 17, label='Coffee Bar',  start = [24, 25], end = [24, 28],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  { id = 18, label='Bar',         start = [29, 26], end = [29, 28],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  { id = 19, label='Bowling Ally',start = [38, 26], end = [38, 28],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  
  { id = 20, label='Roller Rink', start = [14, 30], end = [14, 32],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  { id = 21, label='Comic\nShop', start = [24, 30], end = [24, 32],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  { id = 22, label='Spices',      start = [28, 30], end = [28, 32],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  { id = 23, label='Pawn Shop',   start = [31, 30], end = [31, 32],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  { id = 24, label='Rack',        start = [35, 30], end = [35, 32],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  { id = 25, label='Barbershop',  start = [39, 30], end = [39, 32],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  { id = 26, label='Salon',       start = [45, 30], end = [45, 32],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  { id = 27, label='Fortune',     start = [48, 30], end = [48, 32],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  
  { id = 28, label='Park Street', start = [7, 43], end = [39, 43],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  { id = 29, label='Park Ave', start = [14, 40], end = [14, 42],  lanes=2, color=[211, 211, 211], renderer='ot_street_renderer', update_method='ot_update_interstate'},
  
]

# The short segments that. A street can have many segments since they could attach to businesses, houses, etc. 
# junctions = [
  
# ]

# Ideally, I should be able to toggle off/on the streets/nav graph/houses/agents
# as UI layers.

# An idea is to have phases that coroutines can be assigned to.
# Possible Phases: pre_sim, per_frame, post_sim
# The default would be per_frame so you don't have to specify it every time.
# [[scene.schedule]]
# coroutine = 'bootstrap_town_population'
# phase = 'pre_start'

# TODO:
# - Update the buildings to use units in Cells rather than pixels.

