[simulation.ui]
title = 'Our Town'
description = 'A simulation of a small town.'
instructions = 'Click the start button to begin the simulation.'

# Can I ditch these?
[registered_functions]
renderers = ['ot_building_renderer']
tasks = ['bootstrap_town_population']

[scene]
cell_size = [20, 20]
height = 5000

# Define the factory
[[scene.entities.factories]]
id = 1
title = "The Factory"
location = [240, 10]
width = 800
height = 110
color=[0, 0, 0]
fill=[221, 160, 221]
renderer='ot_building_renderer'
update_method='ot_update_building'

# Define the schools
[scene.entities]
schools = [
  { id = 1, title = "Elementry School",   location = [240, 160], width = 160, height = 60, color=[0, 0, 0], fill=[0, 249, 153], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 2, title = "Middle School",      location = [460, 160], width = 160, height = 60, color=[0, 0, 0], fill=[0, 249, 153], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 3, title = "High School",        location = [680, 160], width = 160, height = 60, color=[0, 0, 0], fill=[0, 249, 153], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 4, title = "Community College",  location = [240, 280], width = 160, height = 60, color=[0, 0, 0], fill=[0, 250, 120], renderer='ot_building_renderer', update_method='ot_update_building'},
  { id = 5, title = "University",         location = [460, 280], width = 200, height = 60, color=[0, 0, 0], fill=[0, 250, 120], renderer='ot_building_renderer', update_method='ot_update_building' }  
]

churches = [
  { id = 1, title = "Temple",           location = [240, 400], width = 60, height = 60, color=[0, 0, 0], fill=[229, 229, 249], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 2, title = "Mosque",           location = [360, 400], width = 60, height = 60, color=[0, 0, 0], fill=[229, 229, 249], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 3, title = "Presbyterian",     location = [480, 400], width = 60, height = 60, color=[0, 0, 0], fill=[229, 229, 249], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 4, title = "Catholic Church",  location = [600, 400], width = 60, height = 60, color=[0, 0, 0], fill=[229, 229, 249], renderer='ot_building_renderer', update_method='ot_update_building' }
]

main_street_businesses = [
  { id = 1, title = "Murv's\nDiner",          location = [240, 520], width = 60, height = 60, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 2, title = "Fancy Pants\nResturant", location = [320, 520], width = 120, height = 60, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 3, title = "Coffee\nBar",            location = [460, 520], width = 40, height = 40, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 4, title = "Bar",                    location = [540, 520], width = 60, height = 60, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 5, title = "Bowling Ally",           location = [620, 520], width = 200, height = 60, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
  
  
  { id = 6, title = "Roller Rink",        location = [240, 640], width = 200, height = 60, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 7, title = "Comic\nShop",        location = [460, 640], width = 60, height = 60, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 8, title = "Dis Ol'\nSpice",     location = [540, 640], width = 40, height = 60, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 9, title = "Pawn\nShop",         location = [600, 640], width = 60, height = 60, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 10, title = "Discount\nRack",    location = [680, 640], width = 60, height = 60, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 11, title = "Barbershop",        location = [760, 640], width = 40, height = 60, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 12, title = "Salon",             location = [820, 640], width = 40, height = 60, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 13, title = "Fortune\nTeller",   location = [880, 640], width = 40, height = 60, color=[0, 0, 0], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
]

parks = [
  { id = 1, title = "Peaceful Park",      location = [240, 720], width = 520, height = 80, color=[100, 230, 100], fill=[100, 230, 100], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 2, title = "Last Stop Cemetery", location = [780, 780], width = 260, height = 100, color=[100, 230, 100], fill=[100, 230, 100], renderer='ot_building_renderer', update_method='ot_update_building' },
]

gov_buildings = [
  { id = 1, title = "City Hall",location = [240, 860], width = 80, height = 80, color=[60, 230, 100], fill=[216, 112, 214], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 2, title = "Court",    location = [340, 860], width = 60, height = 80, color=[100, 230, 100], fill=[216, 112, 214], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 3, title = "Jail",     location = [420, 880], width = 120, height = 60, color=[100, 230, 100], fill=[216, 112, 214], renderer='ot_building_renderer', update_method='ot_update_building' },
  { id = 4, title = "Prison",   location = [560, 860], width = 200, height = 80, color=[100, 230, 100], fill=[216, 112, 214], renderer='ot_building_renderer', update_method='ot_update_building' },
]

big_box_stores = [
  { id = 1, title = "Mega-mart", description="Grocery/Home Supply Store", location = [240, 960], width = 600, height = 100, color=[100, 230, 100], fill=[188, 183, 107], renderer='ot_building_renderer', update_method='ot_update_building' },
] 


# Residential Area: Single Family Homes, Apartment Buildings

# An idea is to have phases that coroutines can be assigned to.
# Possible Phases: pre_sim, per_frame, post_sim
# The default would be per_frame so you don't have to specify it every time.
# [[scene.schedule]]
# coroutine = 'bootstrap_town_population'
# phase = 'pre_start'

