[simulation.ui]
title = 'Our Town'
description = 'A simulation of a small town.'
instructions = 'Click the start button to begin the simulation.'

# Can I ditch these?
[registered_functions]
renderers = ['ot_building_renderer']
tasks = ['bootstrap_town_population']

[scene]
cell_size = [20, 20]

# Define the factory
[[scene.entities.buildings]]
id = 1
description = "The Factory"
location = [240, 10]
width = 800
height = 110
color=[0, 0, 0]
fill=[221, 160, 221]
renderer='ot_building_renderer'
update_method='ot_update_building'

# Define the schools
[[scene.entities.buildings]]
id = 2
description = "Elementry School"
location = [240, 160]
width = 160
height = 60
color=[0, 0, 0]
fill=[0, 249, 153]
renderer='ot_building_renderer'
update_method='ot_update_building'

[[scene.entities.buildings]]
id = 3
description = "Middle School"
location = [460, 160]
width = 160
height = 60
color=[0, 0, 0]
fill=[0, 249, 153]
renderer='ot_building_renderer'
update_method='ot_update_building'

[[scene.entities.buildings]]
id = 4
description = "High School"
location = [680, 160]
width = 160
height = 60
color=[0, 0, 0]
fill=[0, 249, 153]
renderer='ot_building_renderer'
update_method='ot_update_building'

[[scene.entities.buildings]]
id = 5
description = "Community College"
location = [240, 280]
width = 160
height = 60
color=[0, 0, 0]
fill=[0, 250, 120]
renderer='ot_building_renderer'
update_method='ot_update_building'

[[scene.entities.buildings]]
id = 6
description = "University"
location = [460, 280]
width = 200
height = 60
color=[0, 0, 0]
fill=[0, 250, 120]
renderer='ot_building_renderer'
update_method='ot_update_building'

# An idea is to have phases that coroutines can be assigned to.
# Possible Phases: pre_sim, per_frame, post_sim
# The default would be per_frame so you don't have to specify it every time.
# [[scene.schedule]]
# coroutine = 'bootstrap_town_population'
# phase = 'pre_start'

