[simulation.ui]
title = 'Pulsing Circle Simulation'
description = 'A single circle that oscillates in size.'
instructions = 'Click the start button to begin the simulation.'

[registered_functions]
renderers = ['simple_circle_renderer']
tasks = ['pulse_circle_coroutine']

[scene]
cell_size = [20, 20]
layers = [
  { label='Grid', renderer='render_grid_layer'},
  { label='Performance Statistics', renderer='render_stats_layer'},
  { label='Entities', renderer='render_entities_layer'}
]

# Define a circle
[[scene.entities.circles]]
id = 1
description='pulsing circle'
default_radius = 20
active_radius = 20
scale = 10
location=[100, 100]
color=[0, 0, 0]
fill=[0, 0, 255]
renderer='simple_circle_renderer'
update_method='update_active_radius'

[[scene.schedule]]
coroutine = 'pulse_circle_coroutine'
circle_id = 1
# run_per_frame = 1
speed = 0.100