class TestVector2d:
  def test_from_vertices(self) -> None:
    ...
  
  def test_scale_vector(self) -> None:
    ...
  
  def test_vector_to_point(self) -> None:
    ...
  
  def test_vector_to_vertex(self) -> None:
    ...
  
  def test_rotate(self) -> None:
    ...
  
  def test_unit(self) -> None:
    ...
  
  def test_length(self) -> None:
    ...
  
  def test_right_hand_perp(self) -> None:
    ...
  
  def test_left_hand_perp(self) -> None:
    ...
  
  def test_project_onto(self) -> None:
    ...
  
  def test_dot_product(self) -> None:
    ...
  
  def test_cross_product(self) -> None:
    ...