[simulation.ui]
title = 'Declarative Motion'
description = 'Finite State Machin (FSM) and Fuzzy Finite State Machine (FFSM) based motion.'
instructions = 'Click the start button to begin the simulation.'

[registered_functions]
renderers = ['circular_path_renderer']
tasks = [
  'agent_traverse_circular_path'
]

[scene]
cell_size = [20, 20]
height = 1300 # In pixels.

layers = [
  { label ='Grid',          renderer = 'render_grid_layer',         show = false},
  { label ='Paths',         renderer = 'render_paths_layer',        show = true},
  { label ='Agents',        renderer = 'render_agents_layer',       show = true},
  { label = "Agent's AABB", renderer = 'render_agents_aabb_layer',  show = false },
]

agents = [
  # A final 4 agents that all rotate at different speeds and directions.
  { id = 1, crest='green', location=[36,18]},
  { id = 2, crest='blue',  location=[44,18]},
]


# Create two circular paths.
[scene.paths]
circular = [
  { id = 1, center = [10, 10], radius = 8, renderer = 'circular_path_renderer'},
  { id = 2, center = [40, 10], radius = 8, renderer = 'circular_path_renderer'}
]

# I'd like to dynamically display the state of each agent on the screen. 
[scene.entities]
state_displays = [
  { id = 1, title = "FSM State",  location = [12, 1], width = 40, height = 5, color=[0, 0, 0], fill=[221, 160, 221], renderer='text_display', update_method='agent_state_display_refresh', related='agent', related_id='1'},  
  { id = 2, title = "FFSM State", location = [12, 1], width = 40, height = 5, color=[0, 0, 0], fill=[221, 160, 221], renderer='text_display', update_method='agent_state_display_refresh', related='agent', related_id='1'}  
]